
path:  C:\Users\PC\Desktop\data # dataset root dir
train: train/images  # train images (relative to 'path')
val: train/images  # val images (relative to 'path')

# Classes
nc: 2
names: ['SignStore', 'Utility Pole Information Plate']
